### ISSUE TITLE
Can't install on mac

### ISSUE THREAD

**Issue by francescopupillo** [t-mullen/wififox#7]
Hi,
I've been having the following issue on my OS Sonoma M1 macbook air:

1898 error code 1
1899 error path /usr/local/lib/node_modules/wififox/node_modules/electron
1900 error command failed
1901 error command sh -c node install.js
1902 error HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v9.4.4/electron-v9.4.4-darwin-arm64.zip
1902 error at EventEmitter. (/usr/local/lib/node_modules/wififox/node_modules/got/source/as-stream.js:35:24)
1902 error at EventEmitter.emit (node:events:518:28)
1902 error at module.exports (/usr/local/lib/node_modules/wififox/node_modules/got/source/get-response.js:22:10)
1902 error at ClientRequest.handleResponse (/usr/local/lib/node_modules/wififox/node_modules/got/source/request-as-event-emitter.js:155:5)
1902 error at Object.onceWrapper (node:events:633:26)
1902 error at ClientRequest.emit (node:events:530:35)
1902 error at origin.emit (/usr/local/lib/node_modules/wififox/node_modules/@szmarczak/http-timer/source/index.js:37:11)
1902 error at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)
1902 error at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
1902 error at TLSSocket.socketOnData (node:_http_client:535:22)
1903 verbose exit 1
1904 timing npm Completed in 2068ms
1905 verbose unfinished npm timer reify 1709596029359
1906 verbose unfinished npm timer reify:build 1709596030838
1907 verbose unfinished npm timer build 1709596030838
1908 verbose unfinished npm timer build:deps 1709596030838
1909 verbose unfinished npm timer build:run:postinstall 1709596030847
1910 verbose unfinished npm timer build:run:postinstall:node_modules/wififox 1709596030847
1911 verbose unfinished npm timer build:run:postinstall:node_modules/wififox/node_modules/electron 1709596030849
1912 verbose code 1

Can someone help me?
Thank you so much

**Comment by Khaomi** [comment]
Hey,

It seems like Electron 8 doesn't support arm natively, so I made a fork that updated everything to electron 30, check if it work for you.

https://github.com/xhayper/wififox/tree/dev
